stages:
  - test
  - deploy

test:
  stage: test
  image: node:12-alpine
  allow_failure: false
  script:
    - yarn install
    - yarn lint
    - yarn test
  cache:
    paths:
      - node_modules

deploy:
  stage: deploy
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
