stages:
  - test
  - build

test:
  stage: test
  image: node:12-alpine
  allow_failure: false
  script:
    - yarn install
    - yarn lint
    - yarn test
  cache:
    paths:
      - node_modules

build:
  stage: build
  image: node:12-alpine
  allow_failure: false
  script:
    - yarn install
    - yarn build
  cache:
    paths:
      - node_modules
  artifacts:
    name: '$CI_PROJECT_NAME-$CI_BUILD_REF'
    paths:
      - build
    expire_in: 1 week
